package org.example.ae.demos.interfaces;

import org.springframework.stereotype.Component;

@Component
public class InterfaceOriginMethodDefaultMethodAnnoFallbackDefaultKotlinInterfaceJavaDemo implements InterfaceOriginMethodDefaultMethodAnnoFallbackDefaultKotlinInterfaceForJava {
}
