// Generated by genParentsMatrix task, DO NOT MODIFY
package org.example.ae.demos.parents

import io.github.resilience4j.circuitbreaker.annotation.CircuitBreaker

@Suppress("unused", "UNUSED_PARAMETER")
open class ParentCase102KotlinParentForKotlin {
    @CircuitBreaker(name = "demo", fallbackMethod = "superFallback")
    open fun greeting(name: String?): String {
        return "parent: hello $name"
    }
}
