// Generated by genParentsMatrix task, DO NOT MODIFY
package org.example.ae.demos.parents

import io.github.resilience4j.circuitbreaker.annotation.CircuitBreaker

@Suppress("unused", "UNUSED_PARAMETER")
@CircuitBreaker(name = "demo", fallbackMethod = "superClassFallback")
open class ParentCase060KotlinParentForKotlin {
}
