rootProject.name = "resilience4j-plays"
include("play01-basic")
include("play02-java-base-beans")
include("play03-openfeign")
include("play04-web")
include("play-anno-effectiveness-basic")
include("play-anno-effectiveness-interfaces-cglib")
include("play-anno-effectiveness-interfaces-jdk")
include("play-anno-effectiveness-supers")
include("play-anno-effectiveness-supers-interfaces-combine")
