spring:
  application.name: resilience4j-play
  cloud:
    circuitbreaker:
      bulkhead:
        resilience4j:
          enabled: true
      resilience4j:
        is-disable-thread-pool: false
        is-disable-time-limiter: false
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 10s
    instances:
      HttpBinFeignApidelayint:
        timeout-duration: 10s
  circuitbreaker:
    instances:
      HttpBinFeignApistatusint:
        minimum-number-of-calls: 16
      httpBinStatus:
        minimum-number-of-calls: 8
      greeting:
        minimum-number-of-calls: 8
  thread-pool-bulkhead:
    instances:
      HttpBinFeignApidelayint:
        queue-capacity: 1
        core-thread-pool-size: 1
        max-thread-pool-size: 1
  bulkhead:
    instances:
      HttpBinFeignApidelayint:
        max-concurrent-calls: 1
        max-wait-duration: 100ms

  ratelimiter:
    instances:
      ktGreetingCtrl:
        limit-for-period: 1
        limit-refresh-period: 5s
        timeout-duration: 100ms
#      httpBinGet:
#      httpBin:
#      httpbin:
#        limit-for-period: 1
#        limit-refresh-period: 5s
#        timeout-duration: 100ms
      ktGreetingMethod:
        limit-for-period: 10
        limit-refresh-period: 5s
        timeout-duration: 100ms
