spring:
  application.name: resilience4j-play
  cloud:
    circuitbreaker:
      bulkhead:
        resilience4j:
          # true by default.
          # NOTICE: Detecting of this setting is ONLY supported by IDEA 2023.3.x and above.
          enabled: true
      resilience4j:
        # false by default
        # NOTICE: Detecting of this setting is ONLY supported by IDEA 2023.3.x and above.
        disable-thread-pool: false
        # false by default
        # NOTICE: Detecting of this setting is ONLY supported by IDEA 2023.3.x and above.
        disable-time-limiter: false
        # false by default
        # NOTICE: Detecting of this setting is ONLY supported by IDEA 2023.3.x and above.
        enable-semaphore-default-bulkhead: false
    openfeign:
      circuitbreaker:
        # false by default
        enabled: true
        alphanumeric-ids:
          # false by default with SpringCloud OpenFeign 3.x, and true by default with SpringCloud OpenFeign 4.x.
          # current: SpringCloud OpenFeign 4.1.1, true by default
          enabled: false

resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 10s
    instances:
      HttpBinFeignApistatusint:
        timeout-duration: 10s
      HttpBinFeignApi#status(int):
        timeout-duration: 10s
  circuitbreaker:
    instances:
      httpBinStatus:
        minimum-number-of-calls: 8
      HttpBinFeignApistatusint:
        minimum-number-of-calls: 16
      HttpBinFeignApi#status(int):
        minimum-number-of-calls: 16
  thread-pool-bulkhead:
    instances:
      HttpBinFeignApistatusint:
        queue-capacity: 1
        core-thread-pool-size: 1
        max-thread-pool-size: 1
      HttpBinFeignApi#status(int):
        queue-capacity: 1
        core-thread-pool-size: 1
        max-thread-pool-size: 1
  bulkhead:
    instances:
      HttpBinFeignApistatusint:
        max-concurrent-calls: 1
        max-wait-duration: 100ms
      HttpBinFeignApi#status(int):
        max-concurrent-calls: 1
        max-wait-duration: 100ms
