package org.example.ae.demos.interfaces

import org.springframework.stereotype.Component

@Component
class InterfaceOriginMethodDefaultMethodAnnoFallbackKotlinInterfaceKotlinDemo :
    InterfaceOriginMethodDefaultMethodAnnoFallbackKotlinInterfaceForKotlin
