// Generated by generateDemo task, DO NOT MODIFY
package org.example.ae.interfaces.jdk.demos;

import org.example.ae.interfaces.jdk.biz.DemoCase;

public interface Case193JavaBaseJavaInterfaceForJava extends DemoCase {

}
