// Generated by generateDemo task, DO NOT MODIFY
package org.example.ae.supers.demos;

import org.example.ae.supers.biz.DemoCase;

public abstract class Case193JavaSuperForKotlin implements DemoCase {

}
