// Generated by generateDemo task, DO NOT MODIFY
package org.example.ae.interfaces.cglib.demos;

import org.example.ae.interfaces.cglib.biz.DemoCase;

public interface Case194JavaInterfaceForKotlin extends DemoCase {

}
