// Generated by generateDemo task, DO NOT MODIFY
package org.example.ae.supers.demos

import org.example.ae.supers.biz.DemoCase

abstract class Case192KotlinSuperForJava : DemoCase {

    abstract fun superClassFallback(name: String?, thr: Throwable?): String

    abstract fun superMethodFallback(name: String?, thr: Throwable?): String

    abstract fun classFallback(name: String?, thr: Throwable?): String

    abstract fun methodFallback(name: String?, thr: Throwable?): String

}
