// Generated by generateDemo task, DO NOT MODIFY
package org.example.ae.supers.demos

import io.github.resilience4j.circuitbreaker.annotation.CircuitBreaker
import org.example.ae.supers.biz.DemoCase
import org.example.ae.supers.biz.Greeting.doGreeting

abstract class Case119KotlinSuperForJava : DemoCase {

    @CircuitBreaker(name = "demo", fallbackMethod = "superMethodFallback")
    override fun greeting(name: String?): String {
        return "super:${doGreeting(name)}"
    }

}
