spring:
  aop:
    # Default to true, use cglib.
    # When set to false, beans that should be aop proxied and
    # has implements any interface will be jdk-proxied.
    proxy-target-class: false # enable jdk-proxy

resilience4j:
  circuitbreaker:
    instances:
      demo:
        minimum-number-of-calls: 100
